-- ============================================================
-- STEP 2: SCHEMA SETUP V2 — Run AFTER schema_cleanup.sql
-- Full, clean schema for CurhatWall
-- ============================================================

-- ── 1. Profiles ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.curhatwall_profiles (
  id          TEXT PRIMARY KEY,          -- Clerk User ID
  username    TEXT NOT NULL UNIQUE,
  full_name   TEXT,
  avatar_seed TEXT,
  hide_email  BOOLEAN DEFAULT false,
  created_at  TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ── 2. Posts ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.curhatwall_posts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES public.curhatwall_profiles(id) ON DELETE CASCADE,
  content      TEXT NOT NULL CHECK (char_length(content) >= 10 AND char_length(content) <= 500),
  is_anonymous BOOLEAN DEFAULT true NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ── 3. Likes ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.curhatwall_likes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES public.curhatwall_profiles(id) ON DELETE CASCADE,
  post_id    BIGINT NOT NULL REFERENCES public.curhatwall_posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  UNIQUE (user_id, post_id)              -- one like per user per post
);

-- ── 4. Comments ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.curhatwall_comments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    BIGINT NOT NULL REFERENCES public.curhatwall_posts(id) ON DELETE CASCADE,
  user_id    TEXT NOT NULL REFERENCES public.curhatwall_profiles(id) ON DELETE CASCADE,
  content    TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ── 5. Enable Row Level Security ─────────────────────────────────────────────
ALTER TABLE public.curhatwall_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curhatwall_posts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curhatwall_likes    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.curhatwall_comments ENABLE ROW LEVEL SECURITY;

-- ── 6. RLS Policies: Profiles ────────────────────────────────────────────────
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.curhatwall_profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile."
  ON public.curhatwall_profiles FOR INSERT WITH CHECK (true); -- via Service Role

CREATE POLICY "Users can update own profile."
  ON public.curhatwall_profiles FOR UPDATE USING (true);      -- via Service Role

-- ── 7. RLS Policies: Posts ───────────────────────────────────────────────────
CREATE POLICY "Anyone can view posts."
  ON public.curhatwall_posts FOR SELECT USING (true);

CREATE POLICY "Users can insert own posts."
  ON public.curhatwall_posts FOR INSERT WITH CHECK (true);    -- via Service Role

CREATE POLICY "Users can delete own posts."
  ON public.curhatwall_posts FOR DELETE USING (true);         -- via Service Role

-- ── 8. RLS Policies: Likes ───────────────────────────────────────────────────
CREATE POLICY "Anyone can view likes."
  ON public.curhatwall_likes FOR SELECT USING (true);

CREATE POLICY "Users can insert own likes."
  ON public.curhatwall_likes FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can delete own likes."
  ON public.curhatwall_likes FOR DELETE USING (true);

-- ── 9. RLS Policies: Comments ────────────────────────────────────────────────
CREATE POLICY "Anyone can view comments."
  ON public.curhatwall_comments FOR SELECT USING (true);

CREATE POLICY "Users can insert own comments."
  ON public.curhatwall_comments FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can delete own comments."
  ON public.curhatwall_comments FOR DELETE USING (true);

-- ── 10. Helper View: per-user stats (used by dashboard) ──────────────────────
-- Returns for a given user:
--   my_posts        = number of posts they authored
--   my_likes_received = total likes on all their posts
--   my_comments_received = total comments on all their posts
CREATE OR REPLACE VIEW public.curhatwall_user_stats AS
SELECT
  p.id                                                  AS user_id,
  COUNT(DISTINCT po.id)                                 AS my_posts,
  COUNT(DISTINCT l.id)                                  AS my_likes_received,
  COUNT(DISTINCT c.id)                                  AS my_comments_received
FROM public.curhatwall_profiles p
LEFT JOIN public.curhatwall_posts    po ON po.user_id = p.id
LEFT JOIN public.curhatwall_likes    l  ON l.post_id  = po.id
LEFT JOIN public.curhatwall_comments c  ON c.post_id  = po.id
GROUP BY p.id;

-- ── 11. Notify PostgREST ──────────────────────────────────────────────────────
NOTIFY pgrst, 'reload schema';
