-- Create Profiles Table (Public Profile Data)
create table public.curhatwall_profiles (
  id uuid not null references auth.users(id) on delete cascade primary key, -- References Auth User
  username text not null unique,
  avatar_seed text,
  created_at timestamptz default now() not null
);

-- Create Posts Table
create table public.curhatwall_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.curhatwall_profiles(id) on delete cascade,
  content text not null check (char_length(content) >= 10 and char_length(content) <= 500),
  category text not null check (category in ('Academic', 'Romance', 'Horror', 'Random', 'Career')),
  background_color text default 'bg-nature-100',
  is_anonymous boolean default true not null,
  created_at timestamptz default now() not null
);

-- Create Likes Table
create table public.curhatwall_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.curhatwall_profiles(id) on delete cascade,
  post_id bigint not null references public.curhatwall_posts(id) on delete cascade,
  created_at timestamptz default now() not null,
  unique (user_id, post_id) -- Prevent duplicate likes
);

-- Create Comments Table
create table public.curhatwall_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.curhatwall_posts(id) on delete cascade,
  user_id uuid not null references public.curhatwall_profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz default now() not null
);

-- Enable Row Level Security (RLS)
alter table public.curhatwall_profiles enable row level security;
alter table public.curhatwall_posts enable row level security;
alter table public.curhatwall_likes enable row level security;
alter table public.curhatwall_comments enable row level security;

-- Policies --

-- Profiles: Public can view, User can edit their own
create policy "Public profiles are viewable by everyone." on public.curhatwall_profiles
  for select using (true);

create policy "Users can insert their own profile." on public.curhatwall_profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.curhatwall_profiles
  for update using (auth.uid() = id);

-- Posts: Public can view coverage
create policy "Everyone can view posts." on public.curhatwall_posts
  for select using (true);

create policy "Authenticated users can create posts." on public.curhatwall_posts
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own posts." on public.curhatwall_posts
  for delete using (auth.uid() = user_id);

-- Likes: View all, Insert/Delete own
create policy "Everyone can view likes." on public.curhatwall_likes
  for select using (true);

create policy "Authenticated users can like posts." on public.curhatwall_likes
  for insert with check (auth.uid() = user_id);

create policy "Users can unlike posts." on public.curhatwall_likes
  for delete using (auth.uid() = user_id);

-- Comments: View all, Insert own
create policy "Everyone can view comments." on public.curhatwall_comments
  for select using (true);

create policy "Authenticated users can comment." on public.curhatwall_comments
  for insert with check (auth.uid() = user_id);

create policy "Users can delete own comments." on public.curhatwall_comments
  for delete using (auth.uid() = user_id);

-- Handle Profile Creation on Sign Up (Trigger)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.curhatwall_profiles (id, username, avatar_seed)
  values (new.id, new.raw_user_meta_data->>'username' || '_' || substr(new.id::text, 1, 6), 'seed-' || new.id); -- Fallback/Default logic
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
